"""password

Revision ID: 130b0e8288d5
Revises: 471bcf46ea6c
Create Date: 2024-01-14 17:57:38.085026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '130b0e8288d5'
down_revision: Union[str, None] = '471bcf46ea6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('password', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')

    # ### end Alembic commands ###
